name: replica
scenes:
  [
    "room0",
    "room1",
    "room2",
    "office0",
    "office1",
    "office2",
    "office3",
    "office4",
  ]
# scenes: ["room1"]
path: /network/scratch/s/sacha.morin/data_openlex/Replica_full
