# @package _global_

defaults:
  - dataset: replica

output_path: /home/mila/k/kumaraditya.gupta/scratch/openlex_query/query_experiments_v9
hydra:
  run:
    dir: ${output_path}/logs/${eval.metric}/${dataset.name}/${oc.env:SLURM_JOB_ID}

pred:
  method: openmask3d_duplicated
  path: /home/mila/k/kumaraditya.gupta/scratch/openlex_query/openlex_results/${pred.method}/${dataset.name}

query:
  path: /home/mila/k/kumaraditya.gupta/scratch/openlex_query/openlex_labels
  level: "l0" # ["l0", "l1", "all"]

masks:
  alignment_mode: "per_mask" # ["per_mask", "global"]
  alignment_threshold: 0.001 # dist threshold for nearest neighbor alignment

eval:
  metric: "ap" # ["rank", "ap"]
  criteria: "top_k" # ["top_k", "clip_threshold"]
  clip_threshold: 0.5
  top_k: 10
  iou_threshold: 0.25 # used for rank only

model:
  device: "cuda"
  type: open_clip
  backbone: ViT-H-14 # ViT-L/14@336px # ViT-H-14
  checkpoint: laion2b_s32b_b79k # options: 'laion2b_s32b_b79k', 'metaclip_fullcc', 'metaclip_altogether', 'dfn5b'
