defaults:
  - paths: paths
  - dataset: segmentation/replica
  - model: open_clip # openai_clip (for openscene) / open_clip
  - _self_

evaluation:
  type: features
  topn: 5
  predictions_path: ${paths.base_prediction_path}/${evaluation.algorithm}/${dataset.name}/${dataset.scene}
  algorithm: concept-graphs
  voxel_downsampling_size: 0.05
  output_path: ${paths.output_path}
  iou: True
  set_ranking: False
  excluded_labels:
    ["wall", "floor", "ceiling", "doorframe", "ledge", "windowledge"]
