defaults:
  - paths: paths
  - dataset: segmentation/replica

evaluation:
  type: features
  topn: 5
  predictions_path: ${paths.base_prediction_path}/${evaluation.algorithm}/${dataset.name}/${dataset.scene}
  algorithm: concept-graphs
  voxel_downsampling_size: 0.05
  output_path: ${paths.output_path}
  iou: True
  set_ranking: False
  excluded_labels:
    ["wall", "floor", "ceiling", "doorframe", "ledge", "windowledge"]

model:
  device: "cpu"
  type: open_clip # openai_clip (for openscene) / open_clip
  backbone: ViT-L/14@336px # ViT-L/14@336px (openscene) # ViT-H-14
  checkpoint: laion2b_s32b_b79k # options: 'laion2b_s32b_b79k', 'metaclip_fullcc', 'metaclip_altogether', 'dfn5b'
