# @package _global_

defaults:
  - paths: paths
  - dataset: query/replica
  - _self_

hydra:
  run:
    dir: ${paths.output_path}/logs/${eval.metric}/${dataset.name}/${now:%Y-%m-%d-%H-%M-%S}

masks:
  alignment_mode: "per_mask" # ["per_mask", "global"]
  alignment_threshold: 0.001 # dist threshold for nearest neighbor alignment

evaluation:
  algorithm: concept-graphs # required
  predictions_path: ${paths.base_prediction_path}/${evaluation.algorithm}/${dataset.name}/${dataset.scene}
  metric: "ap" # ["rank", "ap"]
  criteria: "top_k" # ["top_k", "clip_threshold"]
  clip_threshold: 0.5
  top_k: 10
  iou_threshold: 0.25 # used for rank only
  query_level: "l0" # ["l0", "l1", "all"]

model:
  device: "cuda"
  type: open_clip
  backbone: ViT-H-14 # ViT-L/14@336px # ViT-H-14
  checkpoint: laion2b_s32b_b79k # options: 'laion2b_s32b_b79k', 'metaclip_fullcc', 'metaclip_altogether', 'dfn5b'
