# @package _global_

dataset: replica
scenes: ["room0"]
method: concept-graphs

pred:
  path: /data/openlex_results/${method}/${dataset}

masks:
  alignment_mode: "global" #["per_mask", "global"]
  alignment_threshold: 0.01 # dist threshold for nearest neighbor alignment

output_path: /home/kumaraditya/openlex3d/ap_experiments

gt:
  base_path: /data/concept-graphs/Replica_original

query:
  json_path: /data/openlex_labels

eval:
  metric: "rank" #["rank", "ap"]
  criteria: "top_k" #["top_k", "clip_threshold"]
  clip_threshold: 0.5
  top_k: 10
  iou_threshold: 0.25 # used for rank only

model:
  device: "cuda"
  type: open_clip
  backbone:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
  checkpoint: laion2b_s32b_b79k # options: 'laion2b_s32b_b79k', 'metaclip_fullcc', 'metaclip_altogether', 'dfn5b'