dataset: scannetpp
scene_id: 49a82360aa

pred:
  path: /data/openlex_results/openmask3d/scannetpp

masks:
  alignment_mode: "per_mask" #["per_mask", "global"]
  alignment_threshold: 0.01 # dist threshold for nearest neighbor alignment
  output_path: /home/kumaraditya/openlex3d

gt:
  base_path: /data/concept-graphs/scannetpp_openlex_v2

query:
  json_file: /home/kumaraditya/openlex3d/scannetpp_49a82360aa_merged_reviewed_query_to_object_mapping.json

eval:
  threshold: 0.9

model:
  device: "cuda"
  type: open_clip
  backbone:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
  checkpoint: laion2b_s32b_b79k # options: 'laion2b_s32b_b79k', 'metaclip_fullcc', 'metaclip_altogether', 'dfn5b'