dataset:
  name: "replica"
  scene: "room0"
  path: "/home/matias/datasets/replica" # mandatory
  openlex3d_path: "/home/matias/datasets/openlex3d" # mandatory

evaluation:
  type: features
  predictions_path: /home/matias/datasets/conceptgraphs_output
  algorithm: conceptgraphs
  voxel_downsampling_size: 0.05
  output_path: /home/matias/datasets/openlex3d_output
  excluded_labels: ["wall", "floor", "ceiling"]

model:
  device: "cpu"
  type: open_clip
  backbone:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
  checkpoint: laion2b_s32b_b79k # options: 'laion2b_s32b_b79k', 'metaclip_fullcc', 'metaclip_altogether', 'dfn5b'
