dataset:
  name: "replica"
  scene: "room_0"
  path: /network/scratch/s/sacha.morin/data/Replica_full # mandatory
  openlex3d_path: /network/scratch/s/sacha.morin/openlex/assets # mandatory

evaluation:
  type: features
  predictions_path: /network/scratch/s/sacha.morin/openlex/predictions/concept-graphs/replica/room0
  algorithm: concept-graphs
  voxel_downsampling_size: 0.05
  output_path: /network/scratch/s/sacha.morin/openlex/results
  excluded_labels: ["wall", "floor", "ceiling", "doorframe", "ledge", "windowledge"]

model:
  device: "cpu"
  type: open_clip
  backbone:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
  checkpoint: laion2b_s32b_b79k # options: 'laion2b_s32b_b79k', 'metaclip_fullcc', 'metaclip_altogether', 'dfn5b'
