main:
  device: cuda
  dataset: replica 
  scene_name: room_0
  caption_eval: false
  pred_path: predictions/room_0/02-02-24--00-01-49__room0
  replica_dataset_gt_path: data/Replica-Full
models:
  clip:
    type:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
    checkpoint: checkpoints/laion2b_s32b_b79k.bin # checkpoints/ovseg_clipl14_9a1909.pth checkpoints/laion2b_s32b_b79k.bin
