name: scannetpp
scenes:
  [
    "0a76e06478",
    "1f7cbbdde1",
    "49a82360aa",
    "c0f5742640",
    "fd361ab85f",
    "0a7cc12c0e",
    "8a35ef3cfe",
    "4c5c60fa76",
  ]
path: ${paths.scannetpp_path}
